on:
  # Triggers the workflow on push or pull request events but only for the "Test" branch
  push:
    branches: 
      - Test

jobs:
  regula_tf_job:
    runs-on: ubuntu-latest
    name: Regula Terraform
    steps:
    - uses: actions/checkout@master
    - uses: fugue/regula-action@v3.2.1
      with:
        input_path: gcp-resources/template
        include: gcp-resources/opa-policy

  regula_tf_plan_job:
    runs-on: ubuntu-latest
    name: Regula on a Terraform plan JSON
    steps:
    - uses: actions/checkout@master
    - uses: hashicorp/setup-terraform@v1
      with:
        # See the note below for why this option is necessary.
        terraform_wrapper: false
        terraform_version: 1.0.8

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
          credentials_json: ${{secrets.GCP_SA_KEY}}
          service_account: ${{secrets.GCP_SA_EMAIL}}
          
    - run: |
        cd gcp-resources/template/
        cp ../input-json-file/resources.tfvars.json resources.auto.tfvars.json
        terraform init
        terraform plan -refresh=false -out="plan.tfplan"
        terraform show -json plan.tfplan > plan.json

    - uses: fugue/regula-action@v2.6.1
      with:
        input_path: gcp-resources/template/plan.json
        input_type: tf-plan
        include: gcp-resources/opa-policy