name: OPA Policy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "Test" branch
  push:
    branches: 
      - Test

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  TF-PLAN:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: TF-PLAN
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v1

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
          credentials_json: ${{secrets.GCP_SA_KEY}}
          service_account: ${{secrets.GCP_SA_EMAIL}}

    - run: |
        cd gcp-resources/template/
        terraform init
        terraform plan -var-file="../input-json-file/resources.tfvars.json" -out="../opa-policy/tfplan.plan"
        terraform show -json ../opa-policy/tfplan.plan > ../opa-policy/tf-plan.json
    
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    name: Run-OPA-Tests
    needs: TF-PLAN
    steps:
    - uses: actions/checkout@v3
    - uses: open-policy-agent/setup-opa@v2
      with:
        version: latest
        
    - name: Run OPA Tests
      run: |
        cd gcp-resources/opa-policy/
        pwd; ls -lrt
        opa eval --format pretty --data policy.rego --input ../opa-policy/tf-plan.json "data.terraform"
